//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.19 at 07:22:36 PM GMT+07:00 
//


package ru.geekbrains.spring.wnteredshop.soap;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="prod" type="{http://ru.geekbrais.winteredshop/spring/ws/products}prod"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prod"
})
@XmlRootElement(name = "getProdByIdResponse")
public class GetProdByIdResponse {

    @XmlElement(required = true)
    protected Prod prod;

    /**
     * Gets the value of the prod property.
     * 
     * @return
     *     possible object is
     *     {@link Prod }
     *     
     */
    public Prod getProd() {
        return prod;
    }

    /**
     * Sets the value of the prod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prod }
     *     
     */
    public void setProd(Prod value) {
        this.prod = value;
    }

}
