server:
  port: 8190
  servlet:
    context-path: /winter-carts

integration:
  product-service:
    url: http://localhost:8189/winter/api/v1/products
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

