server:
  port: 8190
  servlet:
    context-path: /winter-cart

integration:
  product-service:
    url: http://localhost:8189/winter-core/api/v1/products
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

cart-service:
  cart-prefix: winter_cart_